const ACTION_SET_MAX_VALUE_GEN = "ACTION_SET_MAX_VALUE_GEN";
const ACTION_SET_MIN_VALUE_GEN = "ACTION_SET_MIN_VALUE_GEN";
const ACTION_SET_GEN_VALUE = "ACTION_SET_GEN_VALUE";

export {ACTION_SET_MAX_VALUE_GEN, ACTION_SET_MIN_VALUE_GEN, ACTION_SET_GEN_VALUE};