export const ACTION_START_CONTINUE_TIMER = "ACTION_START_CONTINUE_TIMER";
export const ACTION_PAUSE_TIMER = "ACTION_PAUSE_TIMER";
export const ACTION_RESET_TIMER = "ACTION_RESET_TIMER";
export const ACTION_SET_TIME_NOW = "ACTION_SET_TIME_NOW";
export const ACTION_OVERFLOW_TIMER = "ACTION_OVERFLOW_TIMER";